const nombre = 'Eduard';
const apellido = 'Eduawrds'
const estudiante = `${nombre} ${apellido}`;
const estudianteMayus = estudiante.toLocaleUpperCase();
const estudianteMinus = estudiante.toLocaleLowerCase;
const numLetras = estudiante.length();
const primNom = nombre[0];
const ultiNom = apellido[-1];
const espacioEstudiante = estudiante.join();
const estudianteNombre = estudiante.includes(nombre);
